// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArwMBeVTo66L7H9UhLy5LWE6ZTw0Fhpjg',
    appId: '1:224954181842:web:fec96aaa06b92d75f7650b',
    messagingSenderId: '224954181842',
    projectId: 'foodappflutter-40ef3',
    authDomain: 'foodappflutter-40ef3.firebaseapp.com',
    databaseURL: 'https://foodappflutter-40ef3-default-rtdb.firebaseio.com',
    storageBucket: 'foodappflutter-40ef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdDRzqBfyW1heIJPIw73VzSzVgHwjPX8',
    appId: '1:224954181842:android:74e73ee8174625e4f7650b',
    messagingSenderId: '224954181842',
    projectId: 'foodappflutter-40ef3',
    databaseURL: 'https://foodappflutter-40ef3-default-rtdb.firebaseio.com',
    storageBucket: 'foodappflutter-40ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DtMOQF8aPeq_dTJkjZC1D2VeEp70PPQ',
    appId: '1:224954181842:ios:a528961d3f55878ff7650b',
    messagingSenderId: '224954181842',
    projectId: 'foodappflutter-40ef3',
    databaseURL: 'https://foodappflutter-40ef3-default-rtdb.firebaseio.com',
    storageBucket: 'foodappflutter-40ef3.appspot.com',
    androidClientId: '224954181842-8js25pmec0coo91vaeve453k6olagd7v.apps.googleusercontent.com',
    iosClientId: '224954181842-otm36ovcjb8c0j4vu2gteh7pk15s6rjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantfoodappflutter',
  );
}
